### ISSUE TITLE
We should bump version of the secp256k1_ios.

### ISSUE THREAD

**Issue by OlegGordiichuk** [TrustWallet/trust-keystore#11]
Example of the pod:

 **pod 'secp256k1_ios', :git => 'https://github.com/shamatar/secp256k1_ios.git'**

**Comment by alejandro-isaza** [comment]
Any particular reason? I was thinking using trezor-crypto instead.

**Comment by ghost** [comment]
@aleph7 that's needed to use web3Swift in Trust project.
