### ISSUE TITLE
[!] Unable to find a specification for `secp256k1_ios (~> 0.1.0)`

### ISSUE THREAD

**Issue by mutou172** [TrustWallet/trust-keystore#16]
[!] Unable to find a specification for `secp256k1_ios (~> 0.1.0)` depended upon by `TrustKeystore`

**Comment by mutou172** [comment]
cocoapods-1.2.1.beta.1
update
now : cocoapods-1.4.0
OK

**Comment by ghost** [comment]
Fixed?

**Comment by ghost** [comment]
Just run `pod install --repo-update`
