### ISSUE TITLE
Replace secp256k1_ios with trezor-crypto

### ISSUE THREAD

**Issue by alejandro-isaza** [TrustWallet/trust-keystore#18]
The TrezorCrypto lib already has this functionality. We should remove this extra dependency.

**Comment by ghost** [comment]
I think we can keep `secp256k1_ios`, but https://github.com/TrustWallet/trust-keystore/issues/17 would be more important to implement first.

**Comment by alejandro-isaza** [comment]
Done!

**Comment by vikmeup** [comment]
Nice work!
