### ISSUE TITLE
Get Mnemonic from keystore

### ISSUE THREAD

**Issue by runryan** [TrustWallet/trust-keystore#33]
I'm a beginner for this and not good at encryption algorithm.  Your code really helps me.
I have a question about Mnemonic. Is it possible to get Mnemonic from keystore or account or wallet? Looking forward for your reply.

**Comment by vikmeup** [comment]
@MobDeveloper163 hey! There is no way to get mnemonic from the private key, that's the benefit of using the mnemonic phrase if you exposed one of the private keys from your HD Wallet, seed phrased won't be exposed!

**Comment by runryan** [comment]
Got it! THX!
