### ISSUE TITLE
Address is different with IMtoken

### ISSUE THREAD

**Issue by runryan** [TrustWallet/trust-keystore#37]
I created mnemonic wallet with Trust-Keystore. Then I imported it into IMToken，I got the same private key, but the address is different. 
I also tried import private key from trust-keystore into IMToken, I got the same key pair. 
Is there something wrong with importing mnemonic or just about the address format?

**Comment by vikmeup** [comment]
@MobDeveloper163 yo! I think derivation Path is different with imToken. We do support meta mask derivation path. 

We gonna support derivation for ImToken in the next builds.

**Comment by runryan** [comment]
@vikmeup I did some tests. Finally I find it's not about derivation path but the mnemonic password. I get the same address with IMToken when I leave the password empty. I got confused between the wallet password and mnemonic encrypted password. TrustKeystore do support IMToken, that's great!
