### ISSUE TITLE
Json-metamask

### ISSUE THREAD

**Issue by Bitpes-stablecoin** [TrustWallet/trust-keystore#42]
Hello :
I am trying to export my json file from trust wallet to metamask.
Show the following error:   Unexpected token & in JSON at position 1
how can I solve that ?
Is trust wallet compatible with metamask?
Thank you very much

**Comment by vikmeup** [comment]
@javiertuerca it is compatible. There is should not be any problem.

Make sure you copy paste same information. Sounds like you have missing characters or wrong indentation, or extra quotes.

**Comment by Bitpes-stablecoin** [comment]
Thank you very much
  The error was caused when copying and pasting the json file to a new txt, a indentation was generated and the file was not recognized.
I already managed to export my wallet to metamask
