### ISSUE TITLE
Creat Account very slow

### ISSUE THREAD

**Issue by xiaoluSF** [TrustWallet/trust-keystore#47]
## TrustKeystore Verision 0.4.1
```
  pod 'TrustKeystore', :git=>'https://github.com/TrustWallet/trust-keystore', :branch=>'master'
```
#### I use KeyStore to create an account, the code is as follows
```
//keyStore
public let documentDir = NSSearchPathForDirectoriesInDomains(FileManager.SearchPathDirectory.documentDirectory, .userDomainMask, true).first ?? ""
public let keyStore = try? KeyStore(keyDirectory: URL(fileURLWithPath: documentDir).appendingPathComponent("ne"))
```
```
    @available(iOS 10.0, *)
    func createAccount(with password: String, completion: @escaping (Result<Account, KeystoreError>) -> Void) {
        DispatchQueue.global(qos: .userInitiated).async {
            let account = self.createAccout(password: password)
            DispatchQueue.main.async {
                completion(.success(account))
            }
        }
    }
    
    func createAccout(password: String) -> Account {
        let account = try! keyStore?.createAccount(password: password, type: .encryptedKey)
        return account!
    }
```
### Thank you  very much.
![image](https://user-images.githubusercontent.com/23251844/41466021-fbb5dd70-70d2-11e8-8f5f-7f4a5bd82b43.png)
![image](https://user-images.githubusercontent.com/23251844/41466065-25c91da2-70d3-11e8-96aa-2b5f75c2db42.png)

**Comment by ghost** [comment]
You need to enable compiler optimizations.

**Comment by xiaoluSF** [comment]
@alejandro-isaza-hs It does not work , still thank you.

**Comment by xiaoluSF** [comment]
I found the most time-consuming code
![image](https://user-images.githubusercontent.com/23251844/41481979-a46995aa-7106-11e8-8705-98ed9de4e790.png)

**Comment by xiaoluSF** [comment]
Surprisingly, in the Trust this code is skipped and there is no explicit execution
what is this？

**Comment by xiaoluSF** [comment]
@vikmeup Can you provide some suggestions？

**Comment by vikmeup** [comment]
@alejandro-isaza-hs has more knowledge on this.

**Comment by alejandro-isaza** [comment]
<img width="1300" alt="screen shot 2018-06-16 at 11 14 22 am" src="https://user-images.githubusercontent.com/167236/41501285-778e46d4-7156-11e8-9e29-29da44888e05.png">

Make sure you have this setting.

**Comment by xiaoluSF** [comment]
@vikmeup thank you very much!

**Comment by xiaoluSF** [comment]
@alejandro-isaza It works,really thank you so much.
