### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by mario-huang** [TrustWallet/trust-keystore#48]
Hi , I think `let aesCipher = try AES(key: decryptionKey.bytes, blockMode: .CTR(iv: crypto.cipherParams.iv.bytes), padding: .noPadding)`
should be
`let aesCipher = try AES(key: decryptionKey.bytes, blockMode: CTR(iv: crypto.cipherParams.iv.bytes), padding: .noPadding)`

**Comment by mario-huang** [comment]
I notice that it was fixed, but not in 0.4.1 version.

**Comment by alejandro-isaza** [comment]
Pushing version 0.4.2 now
