### ISSUE TITLE
Why  use the keystore to get the privateKey too slow?

### ISSUE THREAD

**Issue by Li-Qun** [TrustWallet/trust-keystore#54]
this is the function:"var privateKey = try key.decrypt(password: password)"  //public func decrypt(password: String) throws -> Data
I calculate the total time about 30s+ , so crazy   .
What's wrong with my project? Could you give me some advice to solve that problem?

**Comment by vikmeup** [comment]
@Li-Qun take a look: https://github.com/TrustWallet/trust-keystore/issues/47
