### ISSUE TITLE
Use of unresolved identifier 'CTR'

### ISSUE THREAD

**Issue by yuanjunliang** [TrustWallet/trust-keystore#57]
1. CocoaPods could not find compatible versions for pod "CryptoSwift"(~> 0.10.0)

I delete the version and install success. but when build the error appears.
the error like this
Use of unresolved identifier 'CTR' Did you mean 'CBRK'?

with the function try AES(key: encryptionKey.bytes, blockMode: CTR(iv: cipherParams.iv.bytes), padding: .noPadding)

**Comment by vikmeup** [comment]
Make sure to run latest Xcode

**Comment by alejandro-isaza** [comment]
Also make sure to do `pod install --repo-update`
