### ISSUE TITLE
There is something wrong in the new pod version 0.4.2

### ISSUE THREAD

**Issue by Demons-Bee** [TrustWallet/trust-keystore#60]
![wx20180725-114455](https://user-images.githubusercontent.com/6848088/43178552-9b89a3b2-9000-11e8-9352-23dfaced45fd.png)
![wx20180725-114546](https://user-images.githubusercontent.com/6848088/43178553-9be1bca0-9000-11e8-9abb-8bcb1dd89bbf.png)
![wx20180725-114613](https://user-images.githubusercontent.com/6848088/43178554-9c57bc8e-9000-11e8-9027-485764413ad5.png)

**Comment by vikmeup** [comment]
make sure you have latest Xcode and installed latest changes.

**Comment by alejandro-isaza** [comment]
We made some breaking changes in the latest version. For address do `address.data.hashValue` and `lhs.address.data == rhs.address.data`. Then replace `EthereymCrypto` with `Crypto`

**Comment by Demons-Bee** [comment]
Thanks :)
