### ISSUE TITLE
Slip file is deleted in trust-core, please update this framework

### ISSUE THREAD

**Issue by MrMessy77** [TrustWallet/trust-keystore#68]
'Use of undeclared type 'Slip'' in trust-wallet-ios,because 'slip' file is deleted in trust-core framework.
please update trust-keystore framework and we will use trust-keystore framework in trust-wallet-ios.
thanks.

**Comment by vikmeup** [comment]
Here is a fix for keystore https://github.com/TrustWallet/trust-keystore/pull/67
